# Generated by Django 5.0.2 on 2024-05-22 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bad_reply_name', models.TextField()),
            ],
            options={
                'db_table': 'tbl_bad_reply',
                'ordering': ['-created_date'],
            },
        ),
    ]
