# Generated by Django 5.0.2 on 2024-05-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badreply', '0002_rename_bad_reply_name_badreply_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badreply',
            table='tbl_bad_reply',
        ),
    ]
